version: '3'

networks:
  blog:

services:
  postgresql:
    image: postgres:15
    ports:
      - 5455:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: ${BDD_USERNAME}
      POSTGRES_PASSWORD: ${BDD_PASSWORD}
    networks:
      - blog
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4:7.4
    env_file:
      - .env
    ports:
      - 3500:80
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}'
      - 'PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}'
    volumes:
      - ./configs/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - blog
